name: root
channels:
  - https://repo.continuum.io/pkgs/free
  - defaults
  - conda-forge
dependencies:
  - python=3.6.10
  - pip
  - pytorch
  - tensorflow
  - numpy=1.18.1
  - matplotlib=3.1.3
  - dask=2.11.0
  - python-graphviz=0.13.2
  - pip:
    - cplex==12.8.0.0
    - gams-sdk==0.0.1 --install-option="--gams-ignore=n" --install-option="--gams-ignore-studio=y" --install-option="--gams-remove-examples=y"
